name: 微信运动 # 工作流程的名称
 
on: # 什么时候触发
  push:  # 当有代码推送时触发
  schedule:
    - cron: '0 23,1-13/2 * * *'  # 从7点到21点每两小时执行一次
 
jobs: # 执行的工作
  run_demo_actions:
    runs-on: ubuntu-latest # 在最新版本的 Ubuntu 操作系统环境下运行
    steps: # 要执行的步骤
      - name: Checkout code
        uses: actions/checkout@v3  # 用于将github代码仓库的代码拷贝到工作目录中
 
      - name: Set up Python
        uses: actions/setup-python@v2 # 用于设置 Python 环境，它允许你指定要在工作环境中使用的 Python 版本
        with:
          python-version: '3.9'  # 选择要用的Python版本
 
      - name: Install requirements.txt
        run: | # 安装依赖包
          pip install -r ./requirements.txt 
 
      - name: Run main.py
        run: python main.py # 执行py文件    依据自己代码要运行的py情况而定
